workflows:
  android_apk:
    name: Android APK (walkapp)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Prepare Flutter project (create platform folders)
        script: |
          flutter --version
          if [ ! -d "android" ]; then
            flutter create . --platforms=android
          fi
          flutter pub get
          echo "Injecting Android permissions..."
          MANIFEST="android/app/src/main/AndroidManifest.xml"
          if ! grep -q 'android.permission.ACTIVITY_RECOGNITION' "$MANIFEST"; then
            awk '1; /<uses-sdk/ {print "    <uses-permission android:name=\"android.permission.ACTIVITY_RECOGNITION\"/>"}' "$MANIFEST" > tmp_manifest.xml && mv tmp_manifest.xml "$MANIFEST"
          fi
      - name: Build debug APK
        script: |
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - "${CM_EMAIL}"
        notify:
          success: false
          failure: true
